import {
  MenuBook,
  AccountTree,
  Bolt,
  Timeline,
  Visibility,
  ZoomIn,
  ViewCompact,
  ZoomOut,
  Anchor,
  AllInclusive,
  Hub,
  AutoAwesome,
  AccessibilityNew,
  SettingsEthernet,
  Tune,
  Loop,
  Pattern,
  ForkRight,
  Scale,
  CallMerge,
  Accessibility,
} from '@mui/icons-material';

export const FRACTAL_FRAMEWORK = {
  initialState: {
    label: "Initial State (z₀)",
    prompt: "Record your initial thought or observation...",
    description: "The starting point of exploration",
    color: "#E54D2E",
    icon: MenuBook,
  },
  recursiveElaboration: {
    label: "Recursive Elaboration (z²)",
    prompt: "How does this thought expand and connect to itself?",
    description: "Exploring patterns within the initial thought",
    color: "#30A46C",
    icon: AccountTree,
  },
  transformativeInput: {
    label: "Transformative Input (c)",
    prompt: "What new perspective or information shifts this pattern?",
    description: "Introducing novel elements to transform understanding",
    color: "#6E56CF",
    icon: Bolt,
    anchorSelector: true,
  },
  emergentPattern: {
    label: "Emergent Pattern (new z)",
    prompt: "What new understanding emerges from this process?",
    description: "The evolved insight resulting from the iteration",
    color: "#DC8A0C",
    icon: Timeline,
  },
  metaAwareness: {
    label: "Meta-Awareness",
    prompt: "What patterns do you notice in this thinking process itself?",
    description: "Awareness of the fractal patterns in your thought process",
    color: "#1570EF",
    icon: Visibility,
    metaProperty: true,
  },
  microLevel: {
    label: "Micro Level",
    description: "Focus on individual elements and details",
    color: "#9353D3",
    scaleProperty: true,
    icon: ZoomIn,
  },
  mesoLevel: {
    label: "Meso Level",
    description: "Patterns between elements and relationships",
    color: "#7BD959",
    scaleProperty: true,
    icon: ViewCompact,
  },
  macroLevel: {
    label: "Macro Level",
    description: "Overall themes and conceptual frameworks",
    color: "#FFA629",
    scaleProperty: true,
    icon: ZoomOut,
  },
};

export const THERAPEUTIC_ANCHORS = {
  grounding: {
    name: "present_awareness",
    description: "Establishing awareness of the present moment",
    icon: Anchor,
    color: "#3694FF",
  },
  openness: {
    name: "receptivity_to_experience",
    description: "Allowing experiences without resistance",
    icon: AllInclusive,
    color: "#FF7BBF",
  },
  integration: {
    name: "meaning_construction",
    description: "Connecting insights across domains",
    icon: Hub,
    color: "#9AFF8C",
  },
  transformation: {
    name: "pattern_disruption",
    description: "Altering established patterns",
    icon: AutoAwesome,
    color: "#FFB067",
  },
  embodiment: {
    name: "somatic_awareness",
    description: "Bringing awareness to bodily experience",
    icon: AccessibilityNew,
    color: "#FF9551",
  },
  metaAwareness: {
    name: "pattern_recognition_across_scales",
    description: "Recognizing patterns at different levels",
    icon: SettingsEthernet,
    color: "#67D2FF",
  },
  attentionalFlexibility: {
    name: "dynamic_focus_allocation",
    description: "Shifting attention across levels of detail",
    icon: Tune,
    color: "#9E8CFF",
  },
  iterativeRefinement: {
    name: "recursive_understanding_development",
    description: "Developing understanding through multiple iterations",
    icon: Loop,
    color: "#78D96C",
  },
};

export const interventionTypes = {
  patternRecognition: {
    label: "Pattern Recognition",
    description: "Identifying recurring patterns in thought processes",
    icon: Pattern,
    color: "#3694FF",
  },
  bifurcationPoint: {
    label: "Bifurcation Point",
    description: "Identifying points where thought patterns can diverge",
    icon: ForkRight,
    color: "#FF7BBF",
  },
  scaleShifting: {
    label: "Scale-Shifting",
    description: "Moving between different levels of detail",
    icon: Scale,
    color: "#9AFF8C",
  },
  integration: {
    label: "Integration",
    description: "Connecting insights across different scales",
    icon: CallMerge,
    color: "#FFB067",
  },
  embodiment: {
    label: "Embodiment",
    description: "Bringing awareness to bodily experience",
    icon: Accessibility,
    color: "#FF9551",
  },
}; 